Repository Imageus-OSS/client, pull requests merged in 2021-04, with the labels that each got.

#61 Design/group code tooltip
  src/components/landing/GroupLogin.jsx
  src/scss/landing.scss
Labels: sprint-4

#73 Add invite link area
  src/components/TextInput.jsx
  src/components/dashboard/InviteArea.jsx
  src/components/dashboard/Sidebar.jsx
  src/index.jsx
  src/scss/index.scss
  src/scss/invite-area.scss
  src/scss/sidebar.scss
Labels: sprint-5

#74 Adds image upload modal
  src/components/ImageUploadModal.jsx
  src/components/dashboard/PhotoGrid.jsx
  src/scss/image-upload-modal.scss
Labels: sprint-5

#79 Add create group modal
  src/components/CreateGroupModal.jsx
  src/components/dashboard/PhotoGrid.jsx
  src/components/dashboard/Sidebar.jsx
  src/pages/MainPage.jsx
  src/scss/create-group-modal.scss
  src/scss/image-upload-modal.scss
Labels: sprint-5

#78 Design/join group button
  src/components/dashboard/JoinGroupButton.jsx
  src/components/dashboard/Sidebar.jsx
  src/components/landing/ForgotPassword.jsx
  src/index.jsx
  src/scss/ant-overrides.scss
  src/scss/create-group-modal.scss
  src/scss/image-upload-modal.scss
  src/scss/join-group-button.scss
Labels: sprint-5

#81 Add group list component
  src/components/dashboard/GroupList.jsx
  src/components/dashboard/JoinGroupButton.jsx
  src/components/dashboard/Sidebar.jsx
  src/pages/MainPage.jsx
  src/scss/ant-overrides.scss
  src/scss/button.scss
  src/scss/create-group-modal.scss
  src/scss/group-list.scss
  src/scss/join-group-button.scss
  src/scss/photo-grid.scss
  src/scss/sidebar.scss
Labels: sprint-5

#96 Design/login jwt caching
  src/api/API.js
  src/components/landing/LoginCard.jsx
  src/contexts/UserContext.jsx
  src/pages/MainPage.jsx
Labels: sprint-6

#98 Adds email verification skeleton
  src/api/API.js
  src/components/Button.jsx
  src/components/Card.jsx
  src/components/landing/LoginCard.jsx
  src/components/landing/RegisterCard.jsx
  src/index.jsx
  src/pages/VerifyEmailPage.jsx
  src/scss/ant-overrides.scss
  src/scss/button.scss
  src/scss/invite-area.scss
  src/scss/landing.scss
  src/scss/verify-email-page.scss
Labels: sprint-6

#103 Show and switch groups
  src/components/TextInput.jsx
  src/components/dashboard/GroupList.jsx
  src/components/dashboard/InviteArea.jsx
  src/components/dashboard/PhotoGrid.jsx
  src/components/dashboard/PhotoThumbnail.jsx
  src/components/dashboard/Sidebar.jsx
  src/contexts/GroupStateContext.jsx
  src/contexts/GroupsContextDispatch.jsx
  src/models/groups.js
  src/pages/MainPage.jsx
  src/scss/group-list.scss
  src/scss/invite-area.scss
Labels: sprint-6

#107 Hooks up email verification to the API
  src/api/API.js
  src/components/VerifyEmailModal.jsx
  src/components/landing/LoginCard.jsx
  src/components/landing/RegisterCard.jsx
  src/pages/VerifyEmailPage.jsx
  src/scss/landing.scss
  src/scss/verify-email.modal.scss
Labels: sprint-6

#110 Feature/change fallback
  src/assets/errorimage.png
  src/components/dashboard/PhotoThumbnail.jsx
  src/models/groups.js
Labels: sprint-6

#112 Design/user menu
  src/components/dashboard/Navbar.jsx
  src/components/dashboard/UserMenu.jsx
  src/pages/MainPage.jsx
  src/scss/navbar.scss
Labels: sprint-6

#113 Hooks up group creation to the API
  src/api/API.js
  src/api/APIError.js
  src/components/CreateGroupModal.jsx
  src/components/dashboard/GroupList.jsx
  src/components/dashboard/InviteArea.jsx
  src/components/dashboard/Sidebar.jsx
  src/contexts/GroupsContextDispatch.jsx
  src/pages/MainPage.jsx
Labels: sprint-6

#101 Adds a group invite page
  src/api/API.js
  src/index.jsx
  src/pages/GroupInvitePage.jsx
  src/pages/VerifyEmailPage.jsx
  src/scss/floating-button.scss
  src/scss/group-invite-page.scss
Labels: sprint-6

#122 Adds ability to upload images to groups
  src/api/API.js
  src/components/CreateGroupModal.jsx
  src/components/ImageUploadModal.jsx
  src/components/dashboard/FloatingButton.jsx
  src/components/dashboard/GroupList.jsx
  src/components/dashboard/InviteArea.jsx
  src/components/dashboard/Navbar.jsx
  src/components/dashboard/PhotoGrid.jsx
  src/components/dashboard/PhotoThumbnail.jsx
  src/components/dashboard/Sidebar.jsx
  src/contexts/GroupsContextDispatch.jsx
  src/pages/MainPage.jsx
  src/scss/ant-overrides.scss
  src/scss/image-upload-modal.scss
  src/scss/main-page.scss
  src/scss/navbar.scss
  src/scss/photo-grid.scss
Labels: sprint-6

#125 Feature/join group api
  src/components/dashboard/JoinGroupButton.jsx
Labels: sprint-6

#116 Switch from fetch to axios calls
  package-lock.json
  package.json
  src/api/API.js
  src/components/landing/LoginCard.jsx
  src/pages/MainPage.jsx
Labels: sprint-6

#131 Adds ability to invite members to a group
  src/api/API.js
  src/components/MemberInviteModal.jsx
  src/components/dashboard/GroupList.jsx
  src/components/dashboard/GroupMenuButton.jsx
  src/pages/GroupInvitePage.jsx
  src/pages/MainPage.jsx
  src/scss/ant-overrides.scss
  src/scss/member-invite-modal.scss
Labels: sprint-6

#136 Adds password recovery/reset
  src/api/API.js
  src/components/dashboard/UserMenu.jsx
  src/components/landing/ForgotPassword.jsx
  src/index.jsx
  src/pages/PasswordResetPage.jsx
  src/scss/password-reset-page.scss
Labels: sprint-6

#146 Adds modal to update an account
  package-lock.json
  package.json
  src/api/API.js
  src/components/CreateGroupModal.jsx
  src/components/EditAccountModal.jsx
  src/components/ImageUploadModal.jsx
  src/components/dashboard/GroupList.jsx
  src/components/dashboard/Navbar.jsx
  src/components/dashboard/UserMenu.jsx
  src/contexts/GroupsContextDispatch.jsx
  src/contexts/UserContext.jsx
  src/contexts/UserContextDispatch.jsx
  src/contexts/UserStateContext.jsx
  src/pages/MainPage.jsx
  src/scss/ant-overrides.scss
  src/scss/edit-account-modal.scss
Labels: sprint-6

#147 Feature/leave group
  src/api/API.js
  src/components/dashboard/GroupMenuButton.jsx
  src/components/dashboard/PhotoGrid.jsx
  src/components/dashboard/UserMenu.jsx
  src/contexts/GroupsContextDispatch.jsx
  src/pages/MainPage.jsx
Labels: sprint-7

#148 Hotfix for empty creator list and leaving single group in list.
  src/api/API.js
  src/components/dashboard/GroupMenuButton.jsx
  src/pages/MainPage.jsx
Labels: sprint-7

#149 Adds sockets for image/group updates
  package-lock.json
  package.json
  src/api/API.js
  src/components/CreateGroupModal.jsx
  src/components/dashboard/GroupList.jsx
  src/components/dashboard/GroupMenuButton.jsx
  src/components/dashboard/JoinGroupButton.jsx
  src/contexts/GroupsContextDispatch.jsx
  src/contexts/SocketContext.jsx
  src/pages/MainPage.jsx
Labels: sprint-7

#150 Adds ability to delete a group
  src/api/API.js
  src/components/CreateGroupModal.jsx
  src/components/dashboard/GroupMenuButton.jsx
  src/components/dashboard/JoinGroupButton.jsx
  src/pages/PasswordResetPage.jsx
  src/scss/ant-overrides.scss
  src/scss/password-reset-page.scss
Labels: sprint-7
